name: Flutter Build

on:
  push:
    branches:
      - master  # or any other branch you want to build on push
  pull_request:
    branches:
      - master  # or any other branch you want to build on PR

jobs:
  # Android build job
  android:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4  # Update to the latest version

      # Set up Flutter SDK
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.1'  # Specify the exact stable version here

      # Run Flutter pub get to fetch dependencies
      - name: Install dependencies
        run: flutter pub get

      # Android build step
      - name: Build Android APK
        run: flutter build apk --release

      # Save APK as build artifact
      - name: Upload Android APK
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  # iOS build job
  ios:
    name: Build iOS IPA
    runs-on: macos-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4  # Update to the latest version

      # Set up Flutter SDK
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.1'  # Specify the exact stable version here

      # Run Flutter pub get to fetch dependencies
      - name: Install dependencies
        run: flutter pub get

      # iOS build step
      - name: Build iOS IPA
        run: flutter build ipa --release --no-codesign

      # Upload IPA as build artifact
      - name: Upload iOS IPA
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: ios-ipa
          path: build/ios/ipa/*.ipa
